version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    target-branch: dev
    ignore:
      - dependency-name: "@types/vscode"
