name: Main

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 15
      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
      - name: Install Dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm install
      - name: Run lint check
        run: npm run lint

  check-version:
    # Ensures that the current version is later than the one on the marketplace
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 15
      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
      - name: Install Dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm install
      - name: Check version validity
        run: |
          export EXTENSION_ID=$(jq -r '.publisher' package.json).$(jq -r '.name' package.json)
          export PACKAGE_VERSION=$(jq -r '.version' package.json)
          export MARKETPLACE_VERSION=$(npx vsce show $EXTENSION_ID --json | jq -j '.versions[0].version')
          dpkg --compare-versions $PACKAGE_VERSION "gt" $MARKETPLACE_VERSION

  prepublish-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 15
      - name: Install LilyPond
        run: |
          wget https://lilypond.org/download/binaries/linux-64/lilypond-2.22.1-1.linux-64.sh
          sudo bash lilypond-2.22.1-1.linux-64.sh
          lilypond -v
      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
      - name: Install Dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm install
      - name: Run prepublish
        run: npm run vscode:prepublish

  release:
    # Only release when pushing to master
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs:
      - lint
      - check-version
      - prepublish-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 15
      - name: Install LilyPond
        run: |
          wget https://lilypond.org/download/binaries/linux-64/lilypond-2.22.1-1.linux-64.sh
          sudo bash lilypond-2.22.1-1.linux-64.sh
          lilypond -v
      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
      - name: Install Dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm install
      - name: Get tag version
        id: tag
        run: echo "::set-output name=tag::$(jq -r '.version' package.json)"
      - name: Bump version and push tag
        uses: mathieudutour/github-tag-action@v5.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ steps.tag.outputs.tag }}
      - name: Publish extension
        run: npx vsce publish
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
